'use strict';
// Comment noise is the most repeated defect in this repo's own history, so the two forms of it
// that a machine can judge without guessing are checked here.
//
// Deliberately NOT checked: change-history voice. "used to" and "no longer" have legitimate
// uses in this codebase ("the branch point used to detect COMMITTED changes", "fails when a
// symbol no longer exists"), so a regex flags more good comments than bad ones — and a check
// that cries wolf gets switched off, which is worse than no check. That stays review's job,
// under the rule in CLAUDE.md.
const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');
const { REPO_ROOT } = require('./helpers.js');

const DIRS = [
  path.join(REPO_ROOT, 'plugins', 'ticket-loop', 'hooks'),
  path.join(REPO_ROOT, 'plugins', 'ticket-loop', 'skills', 'ticket-loop', 'scripts'),
  path.join(REPO_ROOT, 'tests'),
];

// Authorship belongs in git, never in the source.
const ATTRIBUTION = /(ai[- ]generated|generated by (an? )?(ai|claude|gpt|copilot|llm)|written by (claude|gpt|copilot)|co-?authored by (claude|gpt))/i;

// Three identical trailing comments in one file is the shape of a comment pasted alongside a
// repeated call, where the call already says what the comment says.
const MIN_REPEATS = 3;

function sources() {
  const out = [];
  for (const dir of DIRS) {
    for (const name of fs.readdirSync(dir).filter((f) => f.endsWith('.js'))) {
      out.push({ file: path.relative(REPO_ROOT, path.join(dir, name)), lines: fs.readFileSync(path.join(dir, name), 'utf8').split(/\r?\n/) });
    }
  }
  return out;
}

const files = sources();

test('no source carries an AI-attribution marker', () => {
  for (const { file, lines } of files) {
    lines.forEach((line, i) => {
      const comment = line.match(/\/\/(.*)$/);
      if (comment) assert.ok(!ATTRIBUTION.test(comment[1]), `${file}:${i + 1} claims authorship: ${line.trim()}`);
    });
  }
});

test('no comment is repeated verbatim across a file', () => {
  for (const { file, lines } of files) {
    const counts = new Map();
    for (const line of lines) {
      // Trailing comments only: a standalone `// ---` divider repeats legitimately.
      const m = line.match(/\S.*?\/\/\s*(.+?)\s*$/);
      if (!m || m[1].length < 12) continue;
      counts.set(m[1], (counts.get(m[1]) || 0) + 1);
    }
    for (const [text, n] of counts) {
      assert.ok(
        n < MIN_REPEATS,
        `${file}: "// ${text}" appears ${n} times — if the code needs it said that often, the code should say it`
      );
    }
  }
});
